job_model_test/urls.py
from django.contrib import admin
from django.urls import path, include
from quiz_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz_app.urls')),
    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('forgot_password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz_app/urls.py
from django.urls import path, include
from . import views


app_name = 'quiz_app'

urlpatterns = [
    path('go/', views.home, name='go'),
    path('', views.home, name='home'),
    path('student/exam_list/', views.exam_list_view, name='exam_list'),
    path('student/quiz_view/<int:id>/<int:pk>/', views.quiz_view, name='quiz_view'),
    path('student/re_exam/<int:pk>/',views.re_exam, name='re_exam'),
    path('result/<int:pk>/', views.result_view, name='result_view'),
    path('exam_status/<int:pk>/', views.exam_status_view, name='exam_status_view'),
    path('get_paid_account/',views.get_paid_account, name='get_paid_account'),
    # path('subject/', views.subject_view, name='subject_view'),
    # path('topic/<int:pk>/' , views.topic_view, name='topic_view'),
    path('teacher/exam_info_input/', views.exam_info_input, name='exam_info_input'),
    path('teacher/exam_info_details/<int:pk>', views.exam_info_details_view, name='exam_info_details'),
    path('teacher/exam_info_update/<int:pk>/',views.exam_info_update, name='exam_info_update'),
    path('teacher/exam_info_delete/<int:pk>/',views.exam_info_delete, name='exam_info_delete'),
    path('teacher/exam_info_publish/<int:pk>/',views.exam_info_publish, name='exam_info_publish'),
    path('teacher/question_input_form/<int:pk>/', views.question_input_form, name='data_input_form'),
    path('teacher/question_check/<int:pk>/', views.question_check_view, name='question_check'),
    path('teacher/question_edit_form/<int:pk>/', views.question_edit, name='question_edit'),
    path('teacher/question_delete/<int:pk>/', views.question_delete, name='question_delete'),
    path('teacher/stu_of_inst/', views.std_info_institu, name='students_of_institution'),
    path('teacher/stud_activ/<int:pk>/', views.stu_activation, name='stud_activat'),
    # path('get_options_by_quiz/<int:pk>/', views.OptionsByQuiz.as_view(), name = 'get_options_by_quiz'),
    path('student/regis/', views.student_regis, name = 'student_regis'),
    path('teacher/regis/', views.teacher_regis, name = 'teacher_regis'),
    # path('student/profile_update/', views.student_profile_update(), name='student_profile_update'),
    # path('teacher/profile_update/', views.teacher_profile_update(), name='teacher_profile_update'),
    path('teacher/dashboard/', views.exam_info_list, name='teacher_dashboard'),
    path('super/dashboard/', views.super_admin_dashboard, name='super_admin_dashboard'),
    # path('super/inst_list_filter/', views.Institution_info_list, name='inst_list_filter'),
    # path('super/make_payment/<int:pk>/', views.make_payment, name='make_payment'),
    # path('super/payment_filter/',views.payment_info_list, name='payment_list_filter'),
    # path('super/student_filter/',views.student_info_filter, name='student_list_filter'),
    # path('super/stud_activ/<int:pk>/', views.super_stu_activation, name='super_stud_activat'),
    # path('super/student_delete/<int:pk>/',views.student_info_delete, name='student_delete'),
    # path('super/teacher_filter/',views.teacher_info_filter, name='teacher_list_filter'),
    # path('super/teacher_delete/<int:pk>/',views.teacher_info_delete, name='teacher_delete'),
    # path('super/teacher_approve<int:pk>/', views.teacher_approve, name='teacher_approve'),
    
    path('export-data/', views.export_data, name='export_data'),
    path('import-data/', views.import_data, name='import_data'),

]

quiz_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from quiz_app.models import Quiz, Option, UserQuizInfo, Student
from django.shortcuts import get_object_or_404
from quiz_app.forms import QuizForm, CreateUserForm, UserLoginForm, CreateStudentForm, CreateTeacherForm, ExaminationInfoForm, PaymentForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout 
from .filters import UserQuizInfoFilter,TeacherInfoFilter, StudentInfoFilter


from django.http import HttpResponse, JsonResponse
from quiz_app.models import Quiz, Option, ExaminationInfo , Teacher, Student,Subject ,InstitutionInfo
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User


import datetime
from django.utils import timezone

import calendar
import time
import json
from tablib import Dataset

from .resources import QuizResource, OptionResource

# def job():
#     print("I'm workent....")





# Create your views here.


# def go(request):
#     try:
#         if request.user.teacher.is_teacher:
#             return redirect('quiz_app:teacher_dashboard')

#     except:
            
#         try:
#             if request.user.student.is_student:
#                 return redirect('quiz_app:exam_list')
#         except:
#             try:
#                 if request.user:
#                     return redirect('quiz_app:super_admin_dashboard')
#             except:
#                 print("Something went wrong")


def home(request):
    d = datetime.timedelta( seconds = 30)
    # print(d)
    # payment_create_function()
    # institution_deactiv()

    # import pdb; pdb.set_trace()
    message = ''
    if request.headers.get('Referer'):
        if (request.headers['Referer'].find('student/regis/') != -1)or (request.headers['Referer'].find('teacher/regis/')!= -1) or (request.headers['Referer'].find('register/')!= -1) :
            message = 'Registration successful'
    
    homepage_message=''
    top_header=''
    if InstitutionInfo.objects.last():
        homepage_message = InstitutionInfo.objects.last().homepage_message
        top_header = InstitutionInfo.objects.last().top_header
    return render(request, 'home.html' ,{'message':message, 'homepage_message':homepage_message, 'top_header':top_header })

###---------------start registration, login, logout, change password ,update profile ---------###


##----- teacher registration-----##

def teacher_regis(request):
    user_form = CreateUserForm()
    teac_form = CreateTeacherForm()
    if request.method == 'POST':
        user_form = CreateUserForm(request.POST)
        teac_form = CreateTeacherForm(request.POST)
        if user_form.is_valid() and teac_form.is_valid() :
            user = user_form.save(commit=False)
            user.is_staff = True
            teacher = teac_form.save(commit=False)
            teacher.user_info = user
            user.save()
            teacher.save()

            return redirect('quiz_app:home')

    context = {'user_form':user_form, 'teac_form': teac_form}
    return render(request, 'teach_regis.html', context)





##----- student registration-----##


def student_regis(request):
    user_form = CreateUserForm()
    stu_form = CreateStudentForm()
    if request.method == 'POST':

        user_form = CreateUserForm(request.POST)
        stu_form = CreateStudentForm(request.POST)
        if user_form.is_valid() and stu_form.is_valid() :
            user = user_form.save()
            user.username = user.username + str(user.id)
            student = stu_form.save(commit=False)
            student.user_info = user
            student.roll_num = user.id
            student.save()

            return redirect('quiz_app:home')

    context = {'user_form':user_form, 'stu_form': stu_form}
    return render(request, 'stu_regis.html', context)






def login_page(request):
#     # all_insti = Institution.objects.all()
#     # for inst in all_insti:
#     #     payment = Payment.objects.create(institution_info=inst)
#     #     payment.save()


    form = UserLoginForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password') 
            user = authenticate(username=username, password=password)
            login(request, user)
            
            try:
                if request.user.teacher.is_teacher:
                    return redirect('quiz_app:teacher_dashboard')

            except:
            
                try:
                    if request.user.student.is_student:
                        return redirect('quiz_app:exam_list')
                except:
                    try:
                        if request.user:
                            return redirect('quiz_app:super_admin_dashboard')
                    except:
                        print("Something went wrong")

            
            


    return render(request, 'login.html', {'form': form})



def logout_view(request):
    logout(request)
    return redirect('quiz_app:home')



###---------------end registration, login, logout, change password ,update profile ---------###






### -----------start only for teacher ----------- ###


@login_required
def exam_info_list(request ):
    exam_info_ls = ExaminationInfo.objects.filter(teacher=request.user.teacher)
    return render(request,'dashboard.html',{'exam_info_ls':exam_info_ls})



            ### ---- for exam info ----##

@login_required
def exam_info_input(request):
    exam_info_form = ExaminationInfoForm()
    if request.method == 'POST':
        exam_info_form = ExaminationInfoForm(request.POST)
        if exam_info_form.is_valid():
            exam_info = exam_info_form.save(commit=False)
            exam_info.teacher = request.user.teacher
            exam_info.save()
            return redirect('quiz_app:teacher_dashboard')

        
    context = {'exam_info_form':exam_info_form}
    return render(request, 'teacher/exam_info_form.html', context)


@login_required
def exam_info_details_view(request, pk):
    exam_info = get_object_or_404(ExaminationInfo, pk=pk)
    return render(request, 'teacher/exam_info_details.html', {'exam_info':exam_info})


@login_required
def exam_info_update(request, pk):
    exam_info = get_object_or_404(ExaminationInfo, pk=pk)
    exam_info_form = ExaminationInfoForm(instance=exam_info)
    if request.method == "POST":
        exam_info_form = ExaminationInfoForm(request.POST, instance=exam_info)
        if exam_info_form.is_valid():
            exam_info = exam_info_form.save(commit=False)
            # exam_info.institution_name = request.user.teacher.institution_name
            exam_info.teacher = request.user.teacher
            exam_info.save()
            return redirect('quiz_app:exam_info_details', pk=pk)

    context = {'exam_info_form':exam_info_form}
    return render(request, 'teacher/exam_info_form.html', context)



@login_required
def exam_info_publish(request, pk):
    exam_info = get_object_or_404(ExaminationInfo, pk=pk)
    exam_info.publish()
    return redirect('quiz_app:exam_info_details', pk=pk)
    

@login_required
def exam_info_status_change(request, pk):
    exam_info = get_object_or_404(ExaminationInfo, pk=pk)
    exam_info.change_status()
    return redirect('quiz_app:teacher_dashboard')

@login_required
def exam_info_delete(request, pk):
    exam_info= get_object_or_404(ExaminationInfo, pk=pk)
    if request.method == "POST":
        exam_info.delete()
        return redirect('quiz_app:teacher_dashboard')
    context = {'pk':pk}
    return render(request, 'teacher/exam_info_delete_view.html', context)




    ### -------question_input, edit ,delete --------###
    

@login_required
def question_input_form(request,pk=0):
    exam_info = ExaminationInfo.objects.get(teacher=request.user.teacher, pk=pk)
    number_of_questions = Quiz.objects.filter(exam_info=exam_info)
    quiz_form = QuizForm()

    if request.method == 'POST' :
        quiz_form = QuizForm(request.POST)
        
        if quiz_form.is_valid():

            quiz_title = quiz_form.cleaned_data['title']
            quiz_hints = quiz_form.cleaned_data['hints']
            quiz = Quiz.objects.create( exam_info=exam_info , title = quiz_title, hints = quiz_hints)
            try:
                options_titels = dict(request.POST)['option_title']
                i = 0 
                for opt_title in options_titels:
                    is_corre = 'is_correct_' + str(i)
                    is_corr = True if dict(request.POST).get(is_corre)[0] == 'True' else False 
                    Option.objects.create(quiz=quiz, title=opt_title, is_correct=is_corr)
                    i= i+1
            except:
                quiz.delete()
                return render(request, 'teacher/forms.html' , { 'quiz_form':quiz_form, 'message': 'Please input your data correctly' })

            else:
                quiz_form = QuizForm()
                return render(request, 'teacher/forms.html' , { 'quiz_form':quiz_form, 'message': 'Submited' ,'number_of_questions':number_of_questions })

                

    return render(request, 'teacher/forms.html' , { 'quiz_form':quiz_form , 'number_of_questions':number_of_questions })




@login_required
def question_check_view(request, pk):
    exam_info = ExaminationInfo.objects.get(teacher=request.user.teacher, pk=pk)
    questions = Quiz.objects.filter(exam_info=exam_info)
    return render(request, 'teacher/check_questions.html', {'questions':questions})





@login_required
def question_edit(request, pk):
    quiz_data = get_object_or_404(Quiz, pk=pk)
    quiz_form = QuizForm(instance=quiz_data)
    options = Option.objects.filter(quiz=quiz_data)

    if request.method == "POST":
        quiz_form = QuizForm(request.POST, instance=quiz_data)

        if quiz_form.is_valid():

quiz_app/templates/dashboard.html
{% extends 'base/base.html' %}

{% block title %}Dashboard{% endblock title %}

{% block content %}
    <!-- Widgets  -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body" style="background-color: rgb(107, 107, 255)">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-1">
                            <i class="fa fa-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                                <div class="stat-text"><span class="count" style="color: white">10</span></div>
                                <div class="stat-heading" style="color: white">Total questions</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body" style="background-color: rgb(78, 179, 78)">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-2">
                            <i class="fa fa-users"></i>
                        </div>
                        <div class="stat-content" >
                            <div class="text-left dib">
                                <div class="stat-text" style="color: white"><span class="count">10</span></div>
                                <div class="stat-heading" style="color: white">published Questions</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body" style="background-color: rgb(199, 72, 72)">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-3">
                            <i class="fa fa-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                                <div class="stat-text"><span class="count" style="color: white">10</span></div>
                                <div class="stat-heading" style="color: white">painding Questions</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body" style="background-color: orchid">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-4">
                            <i class="fa fa-users"></i>
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                                <div class="stat-text"><span class="count" style="color: white">10</span></div>
                                <div class="stat-heading" style="color: white">Total Students</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Widgets -->
    
    <div class="clearfix"></div>

    <!-- Orders -->
    {% if user.teacher.approved %}
    <div class="orders">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="box-title">Examination Information List </h4>
                    </div>
                    <div class="card-body--">
                        <div class="table-stats order-table ov-h">
                            <table class="table ">
                                <thead>
                                    <tr>
                                        <th class="serial">#</th>
                                        <th>Exam Name</th>
                                        <th>Class</th>
                                        <th>Subject</th>
                                        <th>Total time</th>
                                        <th>Published</th>
                                        <th>created Date</th>
                                        <th>Status</th>
                                        <th>actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if exam_info_ls %}
                                    {% for exam_info in exam_info_ls %}
                                    <tr>
                                        <td class="serial">{{ forloop.counter }}</td>
                                        <td>{{ exam_info.exam_name }}</td>
                                        <td>{{ exam_info.class_name }}</td>
                                        <td>{{ exam_info.subject_name }}</td>
                                        <td>{{ exam_info.total_time }}</td>
                                        <td>{{ exam_info.published}}</td>
                                        <td>{{ exam_info.created_date }}</td>
                                        <td>{{ exam_info.status }}
                                            <!-- {% if exam_info.status == 'pending' %}
                                                <a class="btn btn-warning" href="">{{ exam_info.status }}</a>
                                            {% elif exam_info.status == 'created' %}
                                                <a class="btn btn-danger" href="">{{ exam_info.status }}</a>
                                            {% endif %} -->
                                        </td>
                                        <td>
                                            <!-- {% if exam_info.published == False %}
                                            <button><a href="{% url 'quiz_app:exam_info_details' pk=exam_info.pk  %}">details</a></button>
                                            {% else %}
                                                <p>Published</p>
                                            {% endif %} -->
                                            <a class='btn btn-success' role='button' href="{% url 'quiz_app:data_input_form' pk=exam_info.pk  %}" >add data</a>
                                            <a class='btn btn-info' role='button' href="{% url 'quiz_app:question_check' pk=exam_info.pk  %}">check data</a>
                                            <a class='btn btn-warning' role='button' href="{% url 'quiz_app:exam_info_details' pk=exam_info.pk  %}">details</a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                        <tr><td>No Exam Info created</td></tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div> <!-- /.table-stats -->
                    </div>
                </div> <!-- /.card -->
            </div>  <!-- /.col-lg-8 -->

            
        </div>
    </div>

    <!-- {% for teacher in institution.instite.all %}{{teacher}}<br /> {% endfor %} -->
    {% elif user.teacher.approved == False %}
    
     <h3>Contact with : {{ user.teacher.institution_name.by_agent | capfirst }} </h3>
     <h4>Phone Number : {{ user.teacher.institution_name.by_agent.phone_number }}</h4>

    {% endif %}


    {% if user.agent.active %}
    
    <div class="orders">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="box-title">Institution Information List </h4>
                    </div>
                    <div class="card-body--">
                        <div class="table-stats order-table ov-h">
                            <table class="table ">
                                <thead>
                                    <tr>
                                        <th class="serial">#</th>
                                        <th>Name</th>
                                        <th>Number of Teachers</th>
                                        <th>Number of Students</th>
                                        <th>Payment Status</th>
                                        <th>actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if institutions %}
                                    {% for institution in institutions %}
                                    <tr>
                                        <td class="serial">{{ forloop.counter }}</td>
                                        <td>{{ institution.institution_name }}</td>
                                        <td><a class='btn btn-success' role='button' href="{% url 'quiz_app:teacher_list' pk=institution.pk %}" >{{institution.instite.all.count}}</a></td>
                                        <td>{{institution.inst.all.count}}</td>
                                        <td>{{ institution.insti.last.payment_status }}</td>
                                        <td>
                                            <a class='btn btn-success' role='button' href="{% url 'quiz_app:teacher_regis' pk=institution.pk %}" >Add teacher</a>
                                            <a class='btn btn-info' role='button' href="#">Details</a>

                                        </td>
                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                        <tr><td>No institution added</td></tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div> <!-- /.table-stats -->
                    </div>
                </div> <!-- /.card -->
            </div>  <!-- /.col-lg-8 -->

            
        </div>
    </div>
    {% elif user.agent.active == False %}
    <h3>Your account is deactivated</h3>

    {% endif %}
    <!-- /.orders -->


    {% if user.is_superuser %}
    
    <div class="orders">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="box-title">Agent List </h4>
                    </div>
                    <div class="card-body--">
                        <div class="table-stats order-table ov-h">
                            <table class="table ">
                                <thead>
                                    <tr>
                                        <th class="serial">#</th>
                                        <th>Name</th>
                                        <th>Phone Number</th>
                                        <th>Email</th>
                                        <th>actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if agents %}
                                    {% for agent in agents %}

                                    <tr>
                                        <td class="serial">{{ forloop.counter }}</td>
                                        <td>{{ agent.user_info.username }}</td>
                                        <td>{{ agent.phone_number }}</td>

                                        <td>{{ agent.user_info.email }}</td>
                                        <td>
                                            <a class='btn btn-success' role='button' href="#" >Add teacher</a>
                                            <a class='btn btn-info' role='button' href="#">Details</a>

                                        </td>
                                    </tr>

                                    {% endfor %}
                                    {% else %}
                                        <tr><td>No institution added</td></tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div> <!-- /.table-stats -->
                    </div>
                </div> <!-- /.card -->
            </div>  <!-- /.col-lg-8 -->

            
        </div>
    </div>
    {% endif %}
{% endblock content %}

quiz_app/templates/export.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Export Person Data</h1>
    <a href="{% url 'export_person' %}" class="btn btn-primary">Download CSV</a>
{% endblock %}

quiz_app/templates/import.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Import Person Data</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="myfile">Choose CSV file to upload:</label>
            <input type="file" name="myfile" id="myfile">
        </div>
        <button type="submit" class="btn btn-primary">Import</button>
    </form>
{% endblock %}

quiz_app/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
</head>
<body class="bg-light">
    <div class="container">
        <div class="row">
          <div class="col-0 col-sm-2">
          
          </div>
          <div class="col-12 col-sm-8 bg-white shadow rounded-3 p-5 mt-5">
            
            <h3 class="">Login</h3>
            <br />
            <br />
        <form method="POST" action="">
                {% csrf_token %}
                

                {{ form.as_p }}
               
               <a href="{% url 'password_reset' %}" style="color:darkred; text-decoration: none;">Forget Password?</a>
               <br>
               <br>
            <input class="btn btn-info d-inline p-2 px-3 shadow" type="submit" value="Login">


        </form>



        </div>
 
        <div class="col-0 col-sm-2">
            
          </div>
        </div>
    </div>


</body>
</html>




<!-- <label for="username" class="form-label">Username</label>
{{ form.username }}
<P>{{ form.username.errors }}</P> -->

<!-- <input type="text" id="username" name="username" class="form-control" > -->


<!-- <label for="email" class="form-label">Email</label>
{{ form.email }}
<p>{{ form.email.errors }}</p> -->


<!-- <input type="text" id="email" name="email" class="form-control" > -->


<!-- <label for="password1" class="form-label">Password</label>
{{ form.password1 }}
<p>{{ form.password1.errors }}</p> -->

<!-- <input type="password" id="password1" name="password1" class="form-control" > -->


<!-- <label for="password2" class="form-label">Confirm password</label>
{{ form.password2 }}
<p>{{ form.password2.errors }}</p>
<input type="password" id="password2" name="password2" class="form-control" > -->





                <!-- <label for="exam_name" class="form-label">Username</label>
                {{ form.username }} -->
                
                <!-- <input type="text" id="username" name="username" class="form-control" > -->
                <!-- <label for="password" class="form-label">Password</label>
                {{ form.password }}
                <p>{{ form.error }}</p> -->

quiz_app/templates/password_reset_email.html
{% autoescape off %}
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:

{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

Your username, in case you’ve forgotten: {{ user.get_username }}

Thanks for using our site!

The {{ site_name }} team

{% endautoescape %}