job_model_test/urls.py
from django.contrib import admin
from django.urls import path, include
from quiz_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz_app.urls')),
    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('forgot_password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz_app/urls.py
from django.urls import path, include
from . import views


app_name = 'quiz_app'

urlpatterns = [
    path('go/', views.home, name='go'),
    path('', views.home, name='home'),
    path('student/exam_list/', views.exam_list_view, name='exam_list'),
    path('student/quiz_view/<int:id>/<int:pk>/', views.quiz_view, name='quiz_view'),
    path('student/re_exam/<int:pk>/',views.re_exam, name='re_exam'),
    path('result/<int:pk>/', views.result_view, name='result_view'),
    path('exam_status/<int:pk>/', views.exam_status_view, name='exam_status_view'),
    path('get_paid_account/',views.get_paid_account, name='get_paid_account'),
    # path('subject/', views.subject_view, name='subject_view'),
    # path('topic/<int:pk>/' , views.topic_view, name='topic_view'),
    path('teacher/exam_info_input/', views.exam_info_input, name='exam_info_input'),
    path('teacher/exam_info_details/<int:pk>', views.exam_info_details_view, name='exam_info_details'),
    path('teacher/exam_info_update/<int:pk>/',views.exam_info_update, name='exam_info_update'),
    path('teacher/exam_info_delete/<int:pk>/',views.exam_info_delete, name='exam_info_delete'),
    path('teacher/exam_info_publish/<int:pk>/',views.exam_info_publish, name='exam_info_publish'),
    path('teacher/question_input_form/<int:pk>/', views.question_input_form, name='data_input_form'),
    path('teacher/question_check/<int:pk>/', views.question_check_view, name='question_check'),
    path('teacher/question_edit_form/<int:pk>/', views.question_edit, name='question_edit'),
    path('teacher/question_delete/<int:pk>/', views.question_delete, name='question_delete'),
    path('teacher/stu_of_inst/', views.std_info_institu, name='students_of_institution'),
    path('teacher/stud_activ/<int:pk>/', views.stu_activation, name='stud_activat'),
    # path('get_options_by_quiz/<int:pk>/', views.OptionsByQuiz.as_view(), name = 'get_options_by_quiz'),
    path('student/regis/', views.student_regis, name = 'student_regis'),
    path('teacher/regis/', views.teacher_regis, name = 'teacher_regis'),
    # path('student/profile_update/', views.student_profile_update(), name='student_profile_update'),
    # path('teacher/profile_update/', views.teacher_profile_update(), name='teacher_profile_update'),
    path('teacher/dashboard/', views.exam_info_list, name='teacher_dashboard'),
    path('super/dashboard/', views.super_admin_dashboard, name='super_admin_dashboard'),
    # path('super/inst_list_filter/', views.Institution_info_list, name='inst_list_filter'),
    # path('super/make_payment/<int:pk>/', views.make_payment, name='make_payment'),
    # path('super/payment_filter/',views.payment_info_list, name='payment_list_filter'),
    # path('super/student_filter/',views.student_info_filter, name='student_list_filter'),
    # path('super/stud_activ/<int:pk>/', views.super_stu_activation, name='super_stud_activat'),
    # path('super/student_delete/<int:pk>/',views.student_info_delete, name='student_delete'),
    # path('super/teacher_filter/',views.teacher_info_filter, name='teacher_list_filter'),
    # path('super/teacher_delete/<int:pk>/',views.teacher_info_delete, name='teacher_delete'),
    # path('super/teacher_approve<int:pk>/', views.teacher_approve, name='teacher_approve'),
    
    path('export-data/', views.export_data, name='export_data'),
    path('import-data/', views.import_data, name='import_data'),

]

templates/base/base.html
<!doctype html>

{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- test -->       
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <!-- test -->
    
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

    <!-- test -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" /> -->
    <!-- test -->
    <link rel="stylesheet" href="{% static 'bootstrap-5.0.0-dist/css/bootstrap.min.css' %}">
   <style>
    #weatherWidget .currentDesc {
        color: #ffffff!important;
    }
        .traffic-chart {
            min-height: 335px;
        }
        #flotPie1  {
            height: 150px;
        }
        #flotPie1 td {
            padding:3px;
        }
        #flotPie1 table {
            top: 20px!important;
            right: -10px!important;
        }
        .chart-container {
            display: table;
            min-width: 270px ;
            text-align: left;
            padding-top: 10px;
            padding-bottom: 10px;
        }
        #flotLine5  {
             height: 105px;
        }

        #flotBarChart {
            height: 150px;
        }
        #cellPaiChart{
            height: 160px;
        }

    </style>
</head>

<body>
    <!-- Left Panel -->
    {% include 'base/sidebar.html' %}
    <!-- /#left-panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        {% include 'base/navbar.html' %}

        {% block breadcrumbs %}

        {% endblock breadcrumbs %}
        <!-- /#header -->
        <!-- Content -->
        <div class="content">
            <!-- Animated -->
            <div class="animated fadeIn">
                {% block content %}
                {% endblock content %}
            </div>
            <!-- .animated -->
        </div>
        <!-- /.content -->
        <div class="clearfix"></div>
        <!-- Footer -->
        {% include 'base/footer.html' %}
        <!-- /.site-footer -->
    </div>
    <!-- /#right-panel -->

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script> 
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!--  Chart js -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script> -->

    <!--Chartist Chart-->
    <!-- <script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script> -->

    <!-- <script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script> -->

    <!-- <script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script> -->
    <!-- <script src="{% static 'assets/js/init/weather-init.js' %}"></script> -->

    <!-- <script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script> -->


    <!--Local Stuff-->
    <script>
        jQuery(document).ready(function($) {
            "use strict";

            // Pie chart flotPie1
            var piedata = [
                { label: "Desktop visits", data: [[1,32]], color: '#5c6bc0'},
                { label: "Tab visits", data: [[1,33]], color: '#ef5350'},
                { label: "Mobile visits", data: [[1,35]], color: '#66bb6a'}
            ];

            $.plot('#flotPie1', piedata, {
                series: {
                    pie: {
                        show: true,
                        radius: 1,
                        innerRadius: 0.65,
                        label: {
                            show: true,
                            radius: 2/3,
                            threshold: 1
                        },
                        stroke: {
                            width: 0
                        }
                    }
                },
                grid: {
                    hoverable: true,
                    clickable: true
                }
            });
            // Pie chart flotPie1  End
            // cellPaiChart
            var cellPaiChart = [
                { label: "Direct Sell", data: [[1,65]], color: '#5b83de'},
                { label: "Channel Sell", data: [[1,35]], color: '#00bfa5'}
            ];
            $.plot('#cellPaiChart', cellPaiChart, {
                series: {
                    pie: {
                        show: true,
                        stroke: {
                            width: 0
                        }
                    }
                },
                legend: {
                    show: false
                },grid: {
                    hoverable: true,
                    clickable: true
                }

            });
            // cellPaiChart End
            // Line Chart  #flotLine5
            var newCust = [[0, 3], [1, 5], [2,4], [3, 7], [4, 9], [5, 3], [6, 6], [7, 4], [8, 10]];

            var plot = $.plot($('#flotLine5'),[{
                data: newCust,
                label: 'New Data Flow',
                color: '#fff'
            }],
            {
                series: {
                    lines: {
                        show: true,
                        lineColor: '#fff',
                        lineWidth: 2
                    },
                    points: {
                        show: true,
                        fill: true,
                        fillColor: "#ffffff",
                        symbol: "circle",
                        radius: 3
                    },
                    shadowSize: 0
                },
                points: {
                    show: true,
                },
                legend: {
                    show: false
                },
                grid: {
                    show: false
                }
            });
            // Line Chart  #flotLine5 End
            // Traffic Chart using chartist
            if ($('#traffic-chart').length) {
                var chart = new Chartist.Line('#traffic-chart', {
                  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                  series: [
                  [0, 18000, 35000,  25000,  22000,  0],
                  [0, 33000, 15000,  20000,  15000,  300],
                  [0, 15000, 28000,  15000,  30000,  5000]
                  ]
              }, {
                  low: 0,
                  showArea: true,
                  showLine: false,
                  showPoint: false,
                  fullWidth: true,
                  axisX: {
                    showGrid: true
                }
            });

                chart.on('draw', function(data) {
                    if(data.type === 'line' || data.type === 'area') {
                        data.element.animate({
                            d: {
                                begin: 2000 * data.index,
                                dur: 2000,
                                from: data.path.clone().scale(1, 0).translate(0, data.chartRect.height()).stringify(),
                                to: data.path.clone().stringify(),
                                easing: Chartist.Svg.Easing.easeOutQuint
                            }
                        });
                    }
                });
            }
            // Traffic Chart using chartist End
            //Traffic chart chart-js
            if ($('#TrafficChart').length) {
                var ctx = document.getElementById( "TrafficChart" );
                ctx.height = 150;
                var myChart = new Chart( ctx, {
                    type: 'line',
                    data: {
                        labels: [ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul" ],
                        datasets: [
                        {
                            label: "Visit",
                            borderColor: "rgba(4, 73, 203,.09)",
                            borderWidth: "1",
                            backgroundColor: "rgba(4, 73, 203,.5)",
                            data: [ 0, 2900, 5000, 3300, 6000, 3250, 0 ]
                        },
                        {
                            label: "Bounce",
                            borderColor: "rgba(245, 23, 66, 0.9)",
                            borderWidth: "1",
                            backgroundColor: "rgba(245, 23, 66,.5)",
                            pointHighlightStroke: "rgba(245, 23, 66,.5)",
                            data: [ 0, 4200, 4500, 1600, 4200, 1500, 4000 ]
                        },
                        {
                            label: "Targeted",
                            borderColor: "rgba(40, 169, 46, 0.9)",
                            borderWidth: "1",
                            backgroundColor: "rgba(40, 169, 46, .5)",
                            pointHighlightStroke: "rgba(40, 169, 46,.5)",
                            data: [1000, 5200, 3600, 2600, 4200, 5300, 0 ]
                        }
                        ]
                    },
                    options: {
                        responsive: true,
                        tooltips: {
                            mode: 'index',
                            intersect: false
                        },
                        hover: {
                            mode: 'nearest',
                            intersect: true
                        }

                    }
                } );
            }
            //Traffic chart chart-js  End
            // Bar Chart #flotBarChart
            $.plot("#flotBarChart", [{
                data: [[0, 18], [2, 8], [4, 5], [6, 13],[8,5], [10,7],[12,4], [14,6],[16,15], [18, 9],[20,17], [22,7],[24,4], [26,9],[28,11]],
                bars: {
                    show: true,
                    lineWidth: 0,
                    fillColor: '#ffffff8a'
                }
            }], {
                grid: {
                    show: false
                }
            });
            // Bar Chart #flotBarChart End
        });
    </script>
</body>
</html>

templates/base/footer.html
<footer class="site-footer">
    <div class="footer-inner bg-white">
        <div class="row">
            <div class="col-sm-6">
                © 2022 Examination Management System. All Rights Reserved
            </div>
            <div class="col-sm-6 text-right">
                Developed by <a href="https://praised-quiz-project.heorkuapp.com">praised.com</a>
            </div>
        </div>
    </div>
</footer>

templates/base/navbar.html
{% load static %}

<header id="header" class="header" style="background: black">
    <div class="top-left">
        <div class="navbar-header" style="background: black">
            <a class="navbar-brand" style="color: white">Exam Management System</a>

            <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
        </div>
    </div>
    <div class="top-right" >
        <div class="header-menu" >
            <div class="header-left">
                <!-- <button class="search-trigger"><i class="fa fa-search"></i></button>
                <div class="form-inline">
                    <form class="search-form" style="background-color: white">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                        <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                    </form>
                </div> -->
                <span class="search-trigger" style="color:greenyellow;">{{ user.username }}</span>

                <!-- <div class="dropdown for-notification">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="count bg-danger">10</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="notification" style="background-color: skyblue">
                        <p class="red">You have 10 Notification</p>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 1 is Messaging.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 2 is Messaging.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 3 is Messaging.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 4 is Messaging.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 5 is Messaging.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 6 is Messaging.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 7 is Messaging.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 8 is Messaging.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 9 is Messaging.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-user"></i>
                            <p>Client Number 10 is Messaging.</p>
                        </a>
                    </div> 
                </div> -->

                <!-- <div class="dropdown for-message">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-envelope"></i>
                        <span class="count bg-primary">7</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="message" style="background: skyblue">
                        <p class="red">You have 7 Messages</p>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{% static 'images/icons/user.png' %}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Juan DelaCruz</span>
                                <span class="time float-right">Just now</span>
                                <p>Hi Good Afternoon</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{% static 'images/icons/user.png' %}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Pedro Pinduko</span>
                                <span class="time float-right">20 minutes ago</span>
                                <p>How to install pip?</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{% static 'images/icons/user.png' %}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Victor Magtanggol</span>
                                <span class="time float-right">30 minutes ago</span>
                                <p>How to create superuser account?</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{% static 'images/icons/user.png' %}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Kimmy Matillano</span>
                                <span class="time float-right">45 minutes ago</span>
                                <p>How to install this Inventory Management System?</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{% static 'images/icons/user.png' %}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Kevin Zaragosa</span>
                                <span class="time float-right">2 minutes ago</span>
                                <p>How to install pycharm?</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{% static 'images/icons/user.png' %}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Joven Samanting</span>
                                <span class="time float-right">5 minutes ago</span>
                                <p>How to upgrade new version of pip?</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="{% static 'images/icons/user.png' %}"></span>
                            <div class="message media-body">
                                <span class="name float-left">Clarence Dalmacio</span>
                                <span class="time float-right">10 minutes ago</span>
                                <p>How to run this IMS?</p>
                            </div>
                        </a>
                    </div>
                </div> -->
            </div>

            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="{% static 'images/Admin.png' %}" alt="User Avatar">
                </a>

                <div class="user-menu dropdown-menu" style="background: skyblue">
                    <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-power -off"></i>Logout</a>
                </div>
            </div>

        </div>
    </div>
</header>

templates/base/sidebar.html
<aside id="left-panel" class="left-panel" style="background: black">
    <nav class="navbar navbar-expand-sm navbar-default" style="background: black">
        <div id="main-menu" class="main-menu collapse navbar-collapse" style="background: black">
            <ul class="nav navbar-nav">
                {% if user.teacher.approved %}
                <li style="background: black" >
                    <a href="#"><a href="{% url 'quiz_app:teacher_dashboard'%}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a></a>
                </li>
                {% endif %}
                {% if user.agent.active %}
                <li style="background: black" >
                    <a href="#"><a href="{% url 'quiz_app:agent_deshboard'%}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a></a>
                </li>
                {% endif %}
                {% if user.is_superuser  %}
                <li style="background: black" >
                    <a href="#"><a href="{% url 'quiz_app:super_admin_dashboard'%}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a></a>
                </li>
                {% endif %}
                <li class="menu-title" style="color: white">My Status</li><!-- /.menu-title -->
                {% if user.teacher.approved %}
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <a href="{% url 'quiz_app:exam_info_input' %}"><i class="menu-icon fa fa-user"></i>Create Exam Info</a></a>
                </li>
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <a href="{% url 'quiz_app:students_of_institution' %}"><i class="menu-icon fa fa-user"></i>Students' info</a>
                
                </li>

                <li>
                    <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <a href="#"><i class="menu-icon fa fa-user"></i>Result</a> -->
                
                </li>

                {% endif %}

                {% if user.is_superuser %}
                I am super user
                {% endif %}

                <!-- <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-users"></i>Buyer</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="#">Add</a></li>
                        <li><i class="fa fa-th-list" style="color: darkblue"></i><a href="#">View</a></li>
                    </ul>
                </li>


                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-tags"></i>Payment</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href='#'>Add</a></li>
                        <li><i class="fa fa-th-list" style="color: darkblue"></i><a href="#">Payment History</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-list"></i>Product</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="#">Add</a></li>
                        <li><i class="fa fa-th-list" style="color: darkblue"></i><a href="#">View</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-shopping-cart"></i>Order</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="#">Add</a></li>
                        <li><i class="fa fa-th-list" style="color: darkblue"></i><a href="#">View</a></li>
                    </ul>
                </li>

                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-truck"></i>Delivery</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-plus-circle" style="color: darkblue"></i><a href="#">Add</a></li>
                        <li><i class="fa fa-th-list" style="color: darkblue"></i><a href="#">View</a></li>
                    </ul>
                </li> -->
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside>