job_model_test/urls.py
from django.contrib import admin
from django.urls import path, include
from quiz_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz_app.urls')),
    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('forgot_password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz_app/urls.py
from django.urls import path, include
from . import views


app_name = 'quiz_app'

urlpatterns = [
    path('go/', views.home, name='go'),
    path('', views.home, name='home'),
    path('student/exam_list/', views.exam_list_view, name='exam_list'),
    path('student/quiz_view/<int:id>/<int:pk>/', views.quiz_view, name='quiz_view'),
    path('student/re_exam/<int:pk>/',views.re_exam, name='re_exam'),
    path('result/<int:pk>/', views.result_view, name='result_view'),
    path('exam_status/<int:pk>/', views.exam_status_view, name='exam_status_view'),
    path('get_paid_account/',views.get_paid_account, name='get_paid_account'),
    # path('subject/', views.subject_view, name='subject_view'),
    # path('topic/<int:pk>/' , views.topic_view, name='topic_view'),
    path('teacher/exam_info_input/', views.exam_info_input, name='exam_info_input'),
    path('teacher/exam_info_details/<int:pk>', views.exam_info_details_view, name='exam_info_details'),
    path('teacher/exam_info_update/<int:pk>/',views.exam_info_update, name='exam_info_update'),
    path('teacher/exam_info_delete/<int:pk>/',views.exam_info_delete, name='exam_info_delete'),
    path('teacher/exam_info_publish/<int:pk>/',views.exam_info_publish, name='exam_info_publish'),
    path('teacher/question_input_form/<int:pk>/', views.question_input_form, name='data_input_form'),
    path('teacher/question_check/<int:pk>/', views.question_check_view, name='question_check'),
    path('teacher/question_edit_form/<int:pk>/', views.question_edit, name='question_edit'),
    path('teacher/question_delete/<int:pk>/', views.question_delete, name='question_delete'),
    path('teacher/stu_of_inst/', views.std_info_institu, name='students_of_institution'),
    path('teacher/stud_activ/<int:pk>/', views.stu_activation, name='stud_activat'),
    # path('get_options_by_quiz/<int:pk>/', views.OptionsByQuiz.as_view(), name = 'get_options_by_quiz'),
    path('student/regis/', views.student_regis, name = 'student_regis'),
    path('teacher/regis/', views.teacher_regis, name = 'teacher_regis'),
    # path('student/profile_update/', views.student_profile_update(), name='student_profile_update'),
    # path('teacher/profile_update/', views.teacher_profile_update(), name='teacher_profile_update'),
    path('teacher/dashboard/', views.exam_info_list, name='teacher_dashboard'),
    path('super/dashboard/', views.super_admin_dashboard, name='super_admin_dashboard'),
    # path('super/inst_list_filter/', views.Institution_info_list, name='inst_list_filter'),
    # path('super/make_payment/<int:pk>/', views.make_payment, name='make_payment'),
    # path('super/payment_filter/',views.payment_info_list, name='payment_list_filter'),
    # path('super/student_filter/',views.student_info_filter, name='student_list_filter'),
    # path('super/stud_activ/<int:pk>/', views.super_stu_activation, name='super_stud_activat'),
    # path('super/student_delete/<int:pk>/',views.student_info_delete, name='student_delete'),
    # path('super/teacher_filter/',views.teacher_info_filter, name='teacher_list_filter'),
    # path('super/teacher_delete/<int:pk>/',views.teacher_info_delete, name='teacher_delete'),
    # path('super/teacher_approve<int:pk>/', views.teacher_approve, name='teacher_approve'),
    
    path('export-data/', views.export_data, name='export_data'),
    path('import-data/', views.import_data, name='import_data'),

]

quiz_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from quiz_app.models import Quiz, Option, UserQuizInfo, Student
from django.shortcuts import get_object_or_404
from quiz_app.forms import QuizForm, CreateUserForm, UserLoginForm, CreateStudentForm, CreateTeacherForm, ExaminationInfoForm, PaymentForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout 
from .filters import UserQuizInfoFilter,TeacherInfoFilter, StudentInfoFilter


from django.http import HttpResponse, JsonResponse
from quiz_app.models import Quiz, Option, ExaminationInfo , Teacher, Student,Subject ,InstitutionInfo
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User


import datetime
from django.utils import timezone

import calendar
import time
import json
from tablib import Dataset

from .resources import QuizResource, OptionResource

# def job():
#     print("I'm workent....")





# Create your views here.


# def go(request):
#     try:
#         if request.user.teacher.is_teacher:
#             return redirect('quiz_app:teacher_dashboard')

#     except:
            
#         try:
#             if request.user.student.is_student:
#                 return redirect('quiz_app:exam_list')
#         except:
#             try:
#                 if request.user:
#                     return redirect('quiz_app:super_admin_dashboard')
#             except:
#                 print("Something went wrong")


def home(request):
    d = datetime.timedelta( seconds = 30)
    # print(d)
    # payment_create_function()
    # institution_deactiv()

    # import pdb; pdb.set_trace()
    message = ''
    if request.headers.get('Referer'):
        if (request.headers['Referer'].find('student/regis/') != -1)or (request.headers['Referer'].find('teacher/regis/')!= -1) or (request.headers['Referer'].find('register/')!= -1) :
            message = 'Registration successful'
    
    homepage_message=''
    top_header=''
    if InstitutionInfo.objects.last():
        homepage_message = InstitutionInfo.objects.last().homepage_message
        top_header = InstitutionInfo.objects.last().top_header
    return render(request, 'home.html' ,{'message':message, 'homepage_message':homepage_message, 'top_header':top_header })

###---------------start registration, login, logout, change password ,update profile ---------###


##----- teacher registration-----##

def teacher_regis(request):
    user_form = CreateUserForm()
    teac_form = CreateTeacherForm()
    if request.method == 'POST':
        user_form = CreateUserForm(request.POST)
        teac_form = CreateTeacherForm(request.POST)
        if user_form.is_valid() and teac_form.is_valid() :
            user = user_form.save(commit=False)
            user.is_staff = True
            teacher = teac_form.save(commit=False)
            teacher.user_info = user
            user.save()
            teacher.save()

            return redirect('quiz_app:home')

    context = {'user_form':user_form, 'teac_form': teac_form}
    return render(request, 'teach_regis.html', context)





##----- student registration-----##


def student_regis(request):
    user_form = CreateUserForm()
    stu_form = CreateStudentForm()
    if request.method == 'POST':

        user_form = CreateUserForm(request.POST)
        stu_form = CreateStudentForm(request.POST)
        if user_form.is_valid() and stu_form.is_valid() :
            user = user_form.save()
            user.username = user.username + str(user.id)
            student = stu_form.save(commit=False)
            student.user_info = user
            student.roll_num = user.id
            student.save()

            return redirect('quiz_app:home')

    context = {'user_form':user_form, 'stu_form': stu_form}
    return render(request, 'stu_regis.html', context)






def login_page(request):
#     # all_insti = Institution.objects.all()
#     # for inst in all_insti:
#     #     payment = Payment.objects.create(institution_info=inst)
#     #     payment.save()


    form = UserLoginForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password') 
            user = authenticate(username=username, password=password)
            login(request, user)
            
            try:
                if request.user.teacher.is_teacher:
                    return redirect('quiz_app:teacher_dashboard')

            except:
            
                try:
                    if request.user.student.is_student:
                        return redirect('quiz_app:exam_list')
                except:
                    try:
                        if request.user:
                            return redirect('quiz_app:super_admin_dashboard')
                    except:
                        print("Something went wrong")

            
            


    return render(request, 'login.html', {'form': form})



def logout_view(request):
    logout(request)
    return redirect('quiz_app:home')



###---------------end registration, login, logout, change password ,update profile ---------###






### -----------start only for teacher ----------- ###


@login_required
def exam_info_list(request ):
    exam_info_ls = ExaminationInfo.objects.filter(teacher=request.user.teacher)
    return render(request,'dashboard.html',{'exam_info_ls':exam_info_ls})



            ### ---- for exam info ----##

@login_required
def exam_info_input(request):
    exam_info_form = ExaminationInfoForm()
    if request.method == 'POST':
        exam_info_form = ExaminationInfoForm(request.POST)
        if exam_info_form.is_valid():
            exam_info = exam_info_form.save(commit=False)
            exam_info.teacher = request.user.teacher
            exam_info.save()
            return redirect('quiz_app:teacher_dashboard')

        
    context = {'exam_info_form':exam_info_form}
    return render(request, 'teacher/exam_info_form.html', context)


@login_required
def exam_info_details_view(request, pk):
    exam_info = get_object_or_404(ExaminationInfo, pk=pk)
    return render(request, 'teacher/exam_info_details.html', {'exam_info':exam_info})


@login_required
def exam_info_update(request, pk):
    exam_info = get_object_or_404(ExaminationInfo, pk=pk)
    exam_info_form = ExaminationInfoForm(instance=exam_info)
    if request.method == "POST":
        exam_info_form = ExaminationInfoForm(request.POST, instance=exam_info)
        if exam_info_form.is_valid():
            exam_info = exam_info_form.save(commit=False)
            # exam_info.institution_name = request.user.teacher.institution_name
            exam_info.teacher = request.user.teacher
            exam_info.save()
            return redirect('quiz_app:exam_info_details', pk=pk)

    context = {'exam_info_form':exam_info_form}
    return render(request, 'teacher/exam_info_form.html', context)



@login_required
def exam_info_publish(request, pk):
    exam_info = get_object_or_404(ExaminationInfo, pk=pk)
    exam_info.publish()
    return redirect('quiz_app:exam_info_details', pk=pk)
    

@login_required
def exam_info_status_change(request, pk):
    exam_info = get_object_or_404(ExaminationInfo, pk=pk)
    exam_info.change_status()
    return redirect('quiz_app:teacher_dashboard')

@login_required
def exam_info_delete(request, pk):
    exam_info= get_object_or_404(ExaminationInfo, pk=pk)
    if request.method == "POST":
        exam_info.delete()
        return redirect('quiz_app:teacher_dashboard')
    context = {'pk':pk}
    return render(request, 'teacher/exam_info_delete_view.html', context)




    ### -------question_input, edit ,delete --------###
    

@login_required
def question_input_form(request,pk=0):
    exam_info = ExaminationInfo.objects.get(teacher=request.user.teacher, pk=pk)
    number_of_questions = Quiz.objects.filter(exam_info=exam_info)
    quiz_form = QuizForm()

    if request.method == 'POST' :
        quiz_form = QuizForm(request.POST)
        
        if quiz_form.is_valid():

            quiz_title = quiz_form.cleaned_data['title']
            quiz_hints = quiz_form.cleaned_data['hints']
            quiz = Quiz.objects.create( exam_info=exam_info , title = quiz_title, hints = quiz_hints)
            try:
                options_titels = dict(request.POST)['option_title']
                i = 0 
                for opt_title in options_titels:
                    is_corre = 'is_correct_' + str(i)
                    is_corr = True if dict(request.POST).get(is_corre)[0] == 'True' else False 
                    Option.objects.create(quiz=quiz, title=opt_title, is_correct=is_corr)
                    i= i+1
            except:
                quiz.delete()
                return render(request, 'teacher/forms.html' , { 'quiz_form':quiz_form, 'message': 'Please input your data correctly' })

            else:
                quiz_form = QuizForm()
                return render(request, 'teacher/forms.html' , { 'quiz_form':quiz_form, 'message': 'Submited' ,'number_of_questions':number_of_questions })

                

    return render(request, 'teacher/forms.html' , { 'quiz_form':quiz_form , 'number_of_questions':number_of_questions })




@login_required
def question_check_view(request, pk):
    exam_info = ExaminationInfo.objects.get(teacher=request.user.teacher, pk=pk)
    questions = Quiz.objects.filter(exam_info=exam_info)
    return render(request, 'teacher/check_questions.html', {'questions':questions})





@login_required
def question_edit(request, pk):
    quiz_data = get_object_or_404(Quiz, pk=pk)
    quiz_form = QuizForm(instance=quiz_data)
    options = Option.objects.filter(quiz=quiz_data)

    if request.method == "POST":
        quiz_form = QuizForm(request.POST, instance=quiz_data)

        if quiz_form.is_valid():

quiz_app/templates/student/exam_status_view.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body class="bg-light">
    
    <div class="container" onmousedown='return false;' onselectstart='return false;'>




        {% if exam_status %}
        <div class="row">

                <div class="col-0 col-sm-2">
                
                </div>
                <div class="col-12 col-sm-8 bg-white shadow rounded-3 p-5 mt-5">
            {% for que in exam_status %}

                {% if que.status %}
                <!-- <div class="container"> -->

                    <!-- <div class="row row-cols-1"> -->
                    <div class="col card border-success mb-3" style="max-width: 70rem;">
                        <div class="card-header">question No.{{ forloop.counter }}</div>
                        <div class="card-body text-success">
                        <h5 class="card-title">{{que.title}}</h5>
                        <p class="card-text">Your given answer : {% for ans in que.client_given %} <span class="d-inline-block bg-success text-white p-1 m-3">{{ ans }}</span> {% endfor %}</p>
                        </div>
                    </div>
        
                    
                    {% else %}
                    <div class="col card border-danger mb-3" style="max-width: 70rem;">
                        <div class="card-header">question No.{{ forloop.counter }}</div>
                        <div class="card-body text-danger">
                        <h5 class="card-title">{{que.title}}</h5>
                        <p class="card-text">Your given answer : {% for ans in que.client_given %} <span class="d-inline-block bg-danger text-white p-1 m-3">{{ ans }}</span> {% endfor %}</p>
                        </div>
                    </div>
                <!-- </div> -->
                <!-- </div> -->

                {% endif %}
            {% endfor %}
            <div class='d-block'></div>
            
            <div >
                <a class="text-decoration-none mx-4" href="{% url 'quiz_app:exam_list' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Exam List</button></a>
                <a class="text-decoration-none mx-4" href="{% url 'quiz_app:home' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Home</button></a>
            </div>
            
            <br />

        </div>
 
        <div class="col-0 col-sm-2">
    
        </div>

        </div>
        {% endif %}
 
    
    </div>




    
</body>
</html>

quiz_app/templates/student/exam_view.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
</head>
<body class="bg-light">
    
    <div class="container">
        <div class="row">
          <div class="col-0 col-sm-2">
          
          </div>
          <div class="col-12 col-sm-8 bg-white shadow rounded-3 p-5 mt-5">

     <br><br>
     <form method="POST" action="" >
      <h3>{{ activation_message|safe }}</h3>
      {% csrf_token %}
      <label for="phone_number" class="form-label">Bkash Number</label>
      {{ form.phone_number }}
      <br /> <br />
      <input class="btn btn-info d-inline p-2 px-3 shadow" type="submit" value="Submit">
     </form>


</div>
 
<div class="col-0 col-sm-2">
    
  </div>
</div>
</div>
    
   
</body>
</html>

quiz_app/templates/student/exam_view1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
</head>
<body class="bg-light">
    
    <div class="container" onmousedown='return false;' onselectstart='return false;'>
        <div class="row">
          <div class="col-0 col-sm-2">
          
          </div>
          <div class="col-12 col-sm-8 bg-white shadow rounded-3 p-5 mt-5">
{% if user.student %}
    {% if message %}
    <h3>{{ message }}</h3><br><br>
    
    <a class="text-decoration-none mx-4" href="{% url 'logout' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Logout</button></a>
    {% endif %}
    {% if std_exam_info %}
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Examination</th>
            <th scope="col">Subject</th>
            <th scope="col">Time</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
    {% for std_exam in std_exam_info %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ std_exam.exam_name }}</td>
            <td>{{ std_exam.subject_name}}</td>
            <td>{{ std_exam.total_time }}</td>
            {% if std_exam.done %}
                <td><a href="{% url 'quiz_app:re_exam' pk=std_exam.pk %}"><button class="btn btn-info success ml">Re Exam</button></a> <a href="{% url 'quiz_app:quiz_view' id=std_exam.pk pk=0 %}"><button class="btn btn-info success">See Reasult</button></a></td>
            {% else %}
                <td><a href="{% url 'quiz_app:quiz_view' id=std_exam.pk pk=0 %}"><button class="btn btn-info success">Start Exam</button></a></td>
            {% endif %}
        </tr>
        
    {% endfor %}
        </tbody>
    </table>
        {% if not user.student.approved %}
            <a class="text-decoration-none mx-4" href="{% url 'quiz_app:get_paid_account' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Get paid accout</button></a>
        {% endif %}
    <a class="text-decoration-none mx-4" href="{% url 'logout' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Logout</button></a>
    {% endif %}

    {% endif %}


    {% if after_payment_message %}

      <h3>{{ activation_message|safe }}</h3>
      <h3>{{ after_payment_message|safe }}</h3>

      <br /> <br />

     <!--{#  <a class="text-decoration-none mx-4" href="{% url 'quiz_app:subject_list_view' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Back</button></a> #} -->
     <a class="text-decoration-none mx-4" href="{% url 'logout' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Logout</button></a>
    {% endif %}
    

</div>
 
<div class="col-0 col-sm-2">
    
  </div>
</div>
</div>
    
   
</body>
</html>

<!-- filter(exam_done=True,user_info=request.user.student) -->

quiz_app/templates/student/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body class="bg-light">
    <div class="container" onmousedown='return false;' onselectstart='return false;'>
        <div class="row">
          <div class="col-0 col-sm-2">
          
          </div>
          <div class="col-12 col-sm-8 bg-white shadow rounded-3 p-5 mt-5">
            {% if quiz %}
            <div id="demo" class="text-end"></div>
            <div id='start_time' class="d-none">{{ last_user_user_quiz_start_time|date:'r' }}</div>
            {% endif %}
        {% if quiz %}
        <h3>Question: &emsp; {{quiz.title}}</h3>
        {% else %}
        <h1>
            Your Exam Result
        </h1>
        <br />

        <p>Name : {{ request.user.username }}</p>
        
        {{request.user.student.userquizinfo.last}}
            <p>Exam : {{result_info.examination_info}}</p>
            <p>Number of correct answer : {{ result_info.num_of_correct_ans }} </p>
            <p>Your score is : {{ result_info.result }}</p>
            <p>Start time : {{ result_info.start_time}}</p>
            <p>End time : {{ result_info.end_time }}</p>
            <p>Time delta : {{ result_info.time_delta }}</p>

            
            <br />
            <a class="text-decoration-none mx-4" href="{% url 'quiz_app:exam_list' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Exam List</button></a>
            <a class="text-decoration-none mx-4" href="{% url 'logout' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Logout</button></a>
            <a class="text-decoration-none mx-4" href="{% url 'quiz_app:result_view' pk=result_info.examination_info.pk %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Score Board</button></a>
            <a class="text-decoration-none mx-4" href="{% url 'quiz_app:exam_status_view' pk=result_info.pk %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Your Status</button></a>
        {% endif %}
            <br />
            <br />

            <!-- {% if quiz %}
            <button class="btn btn-info float-md-end shadow px-3 mb-5 mb-md-1" type="button" onclick="showHints()">Hints</button>
            <br />
            {% endif %} -->

            <form method="post" id="sub_form">
                {% csrf_token %}

            {% for option in options %}
            <ul style="list-style-type:none;">
                <li>
                    <input type="checkbox" name="{{ option.title }}" id=""> &emsp; {{option.title}}</li>
            </ul>
            {% endfor %}

            {% if error %}
            <span class="h1 text-danger"> {{ error }} </span> 
            {% endif %}

            {% if correct %}
                <span class="h1 text-success">{{ correct }}</span>
            {% endif %}
            <br />
            <br />
            {% if quiz %}
            <input class="btn btn-info d-inline p-2 px-3 shadow" id="sub_button" type="submit" value="Submit">
            {% endif %}

 
            {% if quiz %}
            <a class="text-decoration-none mx-4" href="{% url 'quiz_app:quiz_view' id=quiz.exam_info.pk pk=next_pk  %}" >
            <!-- <button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Next</button> -->
            </a>
            {% endif %}
            

        </form>
        <br />        
            <span id="hints" style="display: none;"><span class="h5">Hints : </span> {{ quiz.hints }}</span>
        <br />



        </div>
 
        <div class="col-0 col-sm-2">
            
          </div>
        </div>
    </div>




    <script>

        const tick = document.getElementById('demo');
        const start_time = new Date(document.getElementById('start_time').innerHTML);
        const form = document.getElementById('sub_form')
        const sub_button = document.getElementById('sub_button')

        setInterval(() => {
            now = new Date()
            let number = parseInt((now-start_time)/1000) ;
            let hour = parseInt(number/3600);
            let munit = parseInt(number/60) - parseInt(hour*60);
            let seco = number - (hour*3600 + munit*60);
            // let hour = parseInt(number/3600)
            // console.log('hello');
            tick.innerHTML = `<h4>${hour}:${munit}:${seco}<h4>`;
            // tick.innerHTML = now-start_time ;
            // number +=1;
            // console.log(number)
        }, 1000);

        form.addEventListener('submit', function() {

            // Disable the submit button
            sub_button.setAttribute('disabled', 'disabled');

            // Change the "Submit" text
            sub_button.value = 'Please wait...';
         
        }, false);


        

    </script>
</body>
</html>

quiz_app/templates/student/result_sheet_student.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body class="bg-light">
    
    <div class="container" onmousedown='return false;' onselectstart='return false;'>

        <h4> {{ message }} </h4>
        {% if results %}
        <div class="row">

          

            <table class="table" style="overflow:scroll;">
                <thead>
                    <tr>
                        <th class="serial">#</th>
                        <th>User Name</th>
                        <!-- <th>Roll No</th> -->
                        <th>Correct Ans</th>
                        <th>Total time</th>
                        <th>Marks</th>

                    </tr>
                </thead>
                <tbody>
                    {% if top_result %}
                    <tr class="bg-warning">
                        <td class="serial text-white">winer</td>
                        <td class="text-white">{{ top_result.user_info.user_info.username }}</td>
                        <!-- <td class="text-white">{{ top_result.user_info.roll_num }}</td> -->
                        <td class="text-white">{{ top_result.num_of_correct_ans }}</td>
                        <td class="text-white">{{ top_result.time_delta }}</td>
                        <td class="text-white">{{ top_result.result }}</td>
                    </tr>
                    
                    {% endif %}

                    {% if results %}
                    {% for result in results %}
                        {% if result.user_info == request.user.student %}
                            <tr class="bg-info">
                                <td class="serial">{{ forloop.counter }}</td>
                                <td>{{ result.user_info.user_info.username }}</td>
                                <!-- <td>{{ result.user_info.roll_num }}</td> -->
                                <td>{{ result.num_of_correct_ans }}</td>
                                <td>{{ result.time_delta }}</td>
                                <td>{{ result.result }}</td>
                            </tr>
                        {% else %}
                            <tr>
                                <td class="serial">{{ forloop.counter }}</td>
                                <td>{{ result.user_info.user_info.username }}</td>
                                <!-- <td>{{ result.user_info.roll_num }}</td> -->
                                <td>{{ result.num_of_correct_ans }}</td>
                                <td>{{ result.time_delta }}</td>
                                <td>{{ result.result }}</td>
                            </tr>

                        {% endif %}
                    {% endfor %}
                    {% else %}
                        <tr><td>No Result</td></tr>
                    {% endif %}
                </tbody>
            </table>

            <div>
                <a class="text-decoration-none mx-4" href="{% url 'quiz_app:exam_list' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Exam List</button></a>
                <a class="text-decoration-none mx-4" href="{% url 'logout' %}" ><button type="button" class="d-inline p-2 px-4 shadow btn btn-info">Home</button></a>
            </div>
            
            <br />



        </div>
        {% endif %}
 
        </div>
    </div>




    
</body>
</html>