job_model_test/urls.py
from django.contrib import admin
from django.urls import path, include
from quiz_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz_app.urls')),
    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('forgot_password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz_app/urls.py
from django.urls import path, include
from . import views


app_name = 'quiz_app'

urlpatterns = [
    path('go/', views.home, name='go'),
    path('', views.home, name='home'),
    path('student/exam_list/', views.exam_list_view, name='exam_list'),
    path('student/quiz_view/<int:id>/<int:pk>/', views.quiz_view, name='quiz_view'),
    path('student/re_exam/<int:pk>/',views.re_exam, name='re_exam'),
    path('result/<int:pk>/', views.result_view, name='result_view'),
    path('exam_status/<int:pk>/', views.exam_status_view, name='exam_status_view'),
    path('get_paid_account/',views.get_paid_account, name='get_paid_account'),
    # path('subject/', views.subject_view, name='subject_view'),
    # path('topic/<int:pk>/' , views.topic_view, name='topic_view'),
    path('teacher/exam_info_input/', views.exam_info_input, name='exam_info_input'),
    path('teacher/exam_info_details/<int:pk>', views.exam_info_details_view, name='exam_info_details'),
    path('teacher/exam_info_update/<int:pk>/',views.exam_info_update, name='exam_info_update'),
    path('teacher/exam_info_delete/<int:pk>/',views.exam_info_delete, name='exam_info_delete'),
    path('teacher/exam_info_publish/<int:pk>/',views.exam_info_publish, name='exam_info_publish'),
    path('teacher/question_input_form/<int:pk>/', views.question_input_form, name='data_input_form'),
    path('teacher/question_check/<int:pk>/', views.question_check_view, name='question_check'),
    path('teacher/question_edit_form/<int:pk>/', views.question_edit, name='question_edit'),
    path('teacher/question_delete/<int:pk>/', views.question_delete, name='question_delete'),
    path('teacher/stu_of_inst/', views.std_info_institu, name='students_of_institution'),
    path('teacher/stud_activ/<int:pk>/', views.stu_activation, name='stud_activat'),
    # path('get_options_by_quiz/<int:pk>/', views.OptionsByQuiz.as_view(), name = 'get_options_by_quiz'),
    path('student/regis/', views.student_regis, name = 'student_regis'),
    path('teacher/regis/', views.teacher_regis, name = 'teacher_regis'),
    # path('student/profile_update/', views.student_profile_update(), name='student_profile_update'),
    # path('teacher/profile_update/', views.teacher_profile_update(), name='teacher_profile_update'),
    path('teacher/dashboard/', views.exam_info_list, name='teacher_dashboard'),
    path('super/dashboard/', views.super_admin_dashboard, name='super_admin_dashboard'),
    # path('super/inst_list_filter/', views.Institution_info_list, name='inst_list_filter'),
    # path('super/make_payment/<int:pk>/', views.make_payment, name='make_payment'),
    # path('super/payment_filter/',views.payment_info_list, name='payment_list_filter'),
    # path('super/student_filter/',views.student_info_filter, name='student_list_filter'),
    # path('super/stud_activ/<int:pk>/', views.super_stu_activation, name='super_stud_activat'),
    # path('super/student_delete/<int:pk>/',views.student_info_delete, name='student_delete'),
    # path('super/teacher_filter/',views.teacher_info_filter, name='teacher_list_filter'),
    # path('super/teacher_delete/<int:pk>/',views.teacher_info_delete, name='teacher_delete'),
    # path('super/teacher_approve<int:pk>/', views.teacher_approve, name='teacher_approve'),
    
    path('export-data/', views.export_data, name='export_data'),
    path('import-data/', views.import_data, name='import_data'),

]

quiz_app/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from ckeditor.fields import RichTextField
import json

# Create your models here.



####.................site info..................####
class InstitutionInfo(models.Model):
    event_name = models.CharField(max_length=250, default='মডেল টেস্ট' )
    top_header = models.CharField(max_length=200, null=True)
    homepage_message = RichTextField(null=True)
    activation_message = RichTextField(null=True)
    after_payment_message = RichTextField(null=True)

    def __str__(self):
        return self.event_name


#####------------------ user info ------------------------#####



class Teacher(models.Model):
    user_info = models.OneToOneField('auth.User', on_delete = models.CASCADE ,blank=True ,null=True)
    phone_number = models.IntegerField(null=True)
    is_teacher = models.BooleanField(default=True)
    approved = models.BooleanField(default=True)

    def __str__(self):
        return self.user_info.username

    def activate_teacher(self):
        self.approved = True
        self.save()
        return None

    def deactivate_teacher(self):
        self.approved=False
        self.save()
        return None


class Student(models.Model):
    user_info = models.OneToOneField('auth.User', on_delete = models.CASCADE ,blank=True ,null=True)
    roll_num = models.IntegerField()
    # total_time = models.DecimalField(max_digits=5,decimal_places=2)
    phone_number = models.IntegerField(null=True)
    is_student = models.BooleanField(default=True)
    approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey('Teacher', on_delete = models.SET_NULL, blank=True, null=True)

    # stu_quiz_info = models.OneToOneField('UserQuizInfo',on_delete = models.RESTRICT)

    def __str__(self):
        return self.user_info.username
        
    
    def activate_student(self):
        self.approved = True
        self.save()
        return None


    def deactivate_student(self):
        self.approved = False
        self.save()
        return None


class Payment(models.Model):
    user_info = models.ForeignKey('Student', related_name='stu_pay_info', on_delete = models.CASCADE, blank=True ,null = True )
    phone_number = models.IntegerField(null=True)


def set_default_quiz_data():
    data = []
    return json.dumps(data)

class UserQuizInfo(models.Model):
    user_info = models.ForeignKey('Student', related_name='stud_info', on_delete = models.CASCADE ,blank=True ,null=True)
    examination_info = models.ForeignKey('ExaminationInfo',related_name='exami_info', on_delete=models.CASCADE, blank=True ,null=True )
    last_answered_quiz_pk = models.IntegerField(default=0)
    num_of_correct_ans = models.IntegerField(default=0)
    data = models.JSONField(default=set_default_quiz_data)
    # num_of_ans_done = models.IntegerField(default=0)
    exam_done = models.BooleanField(default=False)
    start_time = models.DateTimeField(auto_now_add=True, blank=True, null= True)
    end_time = models.DateTimeField(null=True, blank=True)
    time_delta = models.DurationField(null=True, blank=True)

    @property
    def result(self):
        return self.num_of_correct_ans*self.examination_info.per_ques_marks

    def exam_done_ok(self):
        self.exam_done = True
        self.save()
        return None


    def exam_end_time(self):
        self.end_time = timezone.now()
        # self.time_delta = (self.end_time - self.start_time)
        
        self.time_delta = self.end_time - self.start_time
        self.save()
        return None









# class Payment(models.Model):
#     created_date = models.DateTimeField(auto_now_add=True)
#     payment_status = models.BooleanField(default=False)
#     payment_date = models.DateTimeField(null=True, blank=True)
#     institution_info = models.ForeignKey('Institution',related_name='insti', on_delete=models.SET_NULL, null=True, blank=True)


    
#     def make_payment(self):
#         self.payment_status = True
#         self.payment_date = datetime.now()
#         self.save()
#         return None

#     def __str__(self):
#         return str(self.institution_info.institution_name)

    
#####-------------------- Exam info with institution --------------------#####

class Subject(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title



class ExaminationInfo(models.Model):

    STATUS_CHOISE = [
        ('pending','pending'),
        ('created','created')
    ]

    PAY_STATUS_CHOISE = [
        ('free','free'),
        ('paid','paid')
    ]

    exam_name = models.CharField(max_length=200)
    subject_name = models.ForeignKey('Subject', related_name='topic', on_delete=models.SET_NULL, blank=True, null=True)
    teacher = models.ForeignKey('Teacher', related_name= 'teacher_info', on_delete=models.SET_NULL, blank=True, null=True)
    per_ques_marks = models.IntegerField()
    total_time = models.DecimalField(max_digits=5,decimal_places=2)
    status = models.CharField(max_length=10, choices=STATUS_CHOISE, default='pending')
    pay_status = models.CharField(max_length=7, choices=PAY_STATUS_CHOISE, default='free')
    published = models.BooleanField(default=False) 
    created_date = models.DateTimeField(auto_now_add=True, blank=True, null= True)


    def __str__(self):
        return self.exam_name

    def publish(self):
        self.published = True
        self.save()
        return None

    def change_status(self):
        self.status = 'created'
        self.save()
        return None


# class Subject(models.Model):
#     title = models.CharField(max_length=50)

#     def __str__(self):
#         return self.title



# class Topic(models.Model):
#     subject = models.ForeignKey('Subject', related_name='topic', on_delete=models.CASCADE,)
#     title = models.CharField(max_length=70)

#     def __str__(self):
#         return self.title



class Quiz(models.Model):
    exam_info = models.ForeignKey('ExaminationInfo', related_name='exam_data', on_delete=models.SET_NULL , null=True ,blank=True)
    title = models.CharField(max_length=1000)
    hints = models.CharField(max_length=3000, null=True ,blank=True)
    is_approved = models.BooleanField(default=False)


    def __str__(self):
        return self.title

    def approved(self):
        self.is_approved = True
        self.save()
        return None
    



class Option(models.Model):
    quiz = models.ForeignKey('Quiz', related_name='option', on_delete=models.CASCADE,)
    title = models.CharField(max_length=500)
    is_correct = models.BooleanField(default=False)
    

    def __str__(self):
        return self.title

quiz_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from quiz_app.models import Quiz, Student, Teacher, ExaminationInfo, Payment
from django.contrib.auth import authenticate



class QuizForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea)
    hints = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Quiz
        fields = ['exam_info','title', 'hints']
        labels = {
            'title': ('Quiz'),
        }
        widgets = {
            'exam_info' : forms.HiddenInput(attrs={'class': 'form-control'})
        }



class CreateUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
    'class': 'form-control', 'placeholder': ' You can Use email as username'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={
    'class': 'form-control', 'placeholder': 'Type your email' }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
    'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
    'class': 'form-control', 'placeholder': 'Repeat Password'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']





class UserLoginForm(forms.Form):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )

    )
    password = forms.CharField(
        label='Password',
        widget=forms.TextInput(
            attrs={'type': 'password',
            'class': 'form-control'
            }
        )
    )

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            print(user)
            if not user:
                print('not correct')
                raise forms.ValidationError('Incorract credentials')

        return super(UserLoginForm, self).clean(*args, **kwargs)




class CreateStudentForm(forms.ModelForm):
    # institution_name = forms.CharField(widget=forms.TextInput(attrs={
    # 'class': 'form-control', 'placeholder': 'Type your name'}))

    # class_name = forms.Select(widget=forms.TextInput(attrs={
    # 'class': 'form-control', 'placeholder': 'Type your name'}))

    # roll_num = forms.IntegerField(widget=forms.TextInput(attrs={
    # 'class': 'form-control'}))


    class Meta:
        model = Student
        fields = ['user_info','phone_number']
        widgets = {
            'user_info' : forms.HiddenInput(attrs={'class': 'form-control'}),
            'phone_number' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'phone number'}),
        }


class CreateTeacherForm(forms.ModelForm):
    
    class Meta:
        model = Teacher
        fields = ['user_info','phone_number']
        widgets = {
            'user_info' : forms.HiddenInput(attrs={'class': 'form-control'}),
            'phone_number' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Use +88'}),

        }




class ExaminationInfoForm(forms.ModelForm):

    class Meta:
        model = ExaminationInfo
        fields = ['exam_name', 'subject_name', 'teacher', 'per_ques_marks', 'total_time', 'pay_status']
        widgets = {
            'exam_name' :forms.TextInput(attrs={'class': 'form-control'}),
            'subject_name' : forms.Select(attrs={'class': 'form-control'}),
            'teacher' : forms.HiddenInput(attrs={'class': 'form-control'}),
            'per_ques_marks' : forms.NumberInput(attrs={'class': 'form-control'}),
            'total_time' : forms.NumberInput(attrs={'class': 'form-control'}),
            'pay_status' : forms.Select(attrs={'class': 'form-control'}),

        }



class PaymentForm(forms.ModelForm):

    class Meta:
        model = Payment
        fields = ['user_info','phone_number']
        widgets = {
            'user_info' : forms.HiddenInput(attrs={'class': 'form-control'}),
            'phone_number' : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Bkash Number'}),
        }

quiz_app/templates/teacher/check_questions.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <title>Document</title>
    <style>
        ol .flex-container {
            list-Style-position:inside;
            
        }

        .flex-container {
            width:100%;
            display:flex;
            flex-direction: row;
            flex-wrap: wrap;
        }

        .item {
            width: 96%;
            background-color: rgb(240, 240, 240);
            justify-content: space-around;
            margin-left: 4px;
            margin-top: 4px;
            padding-bottom: 8px;
            border-radius: 8px;
        }

        .item>li {
            margin-left: 10px;
        }
        .item>div {
            text-align: right;
        }
        .item>div>a {
            margin-right: 12px;
        }
    </style>
</head>
<body class="bg-light">
    <div class="container">
        <div class="row">
          <div class="col-0 col-sm-2">
          
          </div>
          <div class="col-12 col-sm-8 bg-white shadow rounded-3 p-5 mt-5">
            
            <h3 class="">Check Questions</h3>
            <br />
            <br />
        
            <ol>
                <div class="flex-container">
                    
                            {% for question in questions %}
                            <div class="item">
                            
                            <li>{{ question.title }}</li>
                            <br />
                            <ol type = 'a'>
                                {% for option in question.option.all %}
                                <li>{{ option }} &emsp; &emsp; &emsp; {% if option.is_correct %} status : {{ option.is_correct }} {% endif %}</li>
                                {% endfor %}
                            </ol>
                            
                            <div><a class="btn btn-danger" role="button" href="{% url 'quiz_app:question_delete' pk=question.pk %}">delete</a></Button></div> 
                            
                            </div>
                        {% endfor %}
                    
                </div>
            </ol>
        
        
    <br />
    <div><a class="btn btn-info" role="button" href="{% url 'quiz_app:teacher_dashboard' %}">Go Dashboard</a></Button></div>
</div>  
<div class="col-0 col-sm-2">
          
</div>
</div>
 
</div>


</body>
</html>

quiz_app/templates/teacher/exam_info_delete_view.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body class="bg-light">
    <div class="container">
        <div class="row">
          <div class="col-0 col-sm-2">
          
          </div>
          <div class="col-12 col-sm-8 bg-white shadow rounded-3 p-5 mt-5">
            
            <h3 class="">Examination Information</h3>
            <br />
            <br />
    <form method="POST" action="">
        {% csrf_token %}
        <h3>Are you sure you want to delete this?</h3> 
        <input class="btn btn-danger" type="submit" value="Yes"/>

        <a class="btn btn-warning" role="button" href="{% url 'quiz_app:exam_info_details' pk=pk %}">No </a>
        </form>

    </div>
 
    <div class="col-0 col-sm-2">
        
      </div>
    </div>
    </div>
</body>
</html>

quiz_app/templates/teacher/exam_info_details.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body class="bg-light">
    <div class="container">
        <div class="row">
          <div class="col-0 col-sm-2">
          
          </div>
          <div class="col-12 col-sm-8 bg-white shadow rounded-3 p-5 mt-5">
            
            <h3 class="">Examination Information</h3>
            <br />
            <br />
        <table>
            <tr><td>Institution Name :</td><td>&ensp;&ensp;{{exam_info.institution_name}}</td></tr>
            <tr><td>Exam Name :</td><td>&ensp;&ensp;{{ exam_info.exam_name }}</td></tr> 
            <tr><td>Class :</td><td>&ensp;&ensp;{{ exam_info.class_name }}</td></tr> 
            <tr><td>Subject :</td><td>&ensp;&ensp;{{ exam_info.subject_name }}</td></tr> 
            <tr><td>Teacher :</td><td>&ensp;&ensp;{{ exam_info.teacher }}</td></tr> 
            <tr><td>Marks per question :</td><td>&ensp;&ensp;{{ exam_info.per_ques_marks }}</td></tr> 
            <tr><td>Time duration :</td><td> &ensp;&ensp;{{ exam_info.total_time }}</td></tr>
            <tr><td>Created date :</td><td>&ensp;&ensp;{{ exam_info.created_date }}</td></tr> 
            <tr><td>Status :</td><td> &ensp;&ensp;{{ exam_info.status }}</td></tr>
            <tr><td>Total Qusetion added :</td><td>&ensp;&ensp;{{exam_info.exam_data.count}}</td></tr> 
            <tr><td>Paid or Free :</td><td>&ensp;&ensp;{{exam_info.pay_status}}</td></tr> 

        </table>
        <br />
        {% if exam_info.published %}<br /> <br />
        <h4 class="text-info">this exam is already published</h4> 
      {% else %}
      <a class="btn btn-warning" role="button" href="{% url 'quiz_app:exam_info_publish' pk=exam_info.pk %}">publish</a> 
      {% endif %}
      &ensp;&ensp;<a class="btn btn-success" role="button" href="{% url 'quiz_app:teacher_dashboard' %}">Go Dashboard</a>
      &ensp;&ensp;<a class="btn btn-info" role="button" href="{% url 'quiz_app:exam_info_update' pk=exam_info.pk %}">update</a> &ensp; <a class="btn btn-danger" role="button" href="{% url 'quiz_app:exam_info_delete' pk=exam_info.pk %}">delete</a> 

     

</div>
 
<div class="col-0 col-sm-2">
    
  </div>
</div>
</div>

</body>
</html>

quiz_app/templates/teacher/forms.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <title>Document</title>
    <style>
        .center {
          margin: auto;
          width: 60%;
          border: 3px solid #73AD21;
          padding: 10px;
        }

        input[type=text] {
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        button, .dash {
            width: 48%;
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin-left: 10px;
            margin-right: auto;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: large;
        }



        textarea {
            width: 100%;
            height: 150px;
            padding: 12px 20px;
            box-sizing: border-box;
            border: 2px solid #ccc;
            border-radius: 4px;
            background-color: #f8f8f8;
            font-size: 16px;
            resize: none;
        }
    </style>
</head>
<body>
    <div class="center">
        {% if message %}
           <h3>{{message}}</h3> 
        {% endif %}
        {{ number_of_questions.count | add:1 }} .No Questions <br /> 
        <form method="POST" >
            {% csrf_token %}
            {{quiz_form.as_p}}
            <ol id = "options_group">
                <li class="copy_node">
                        <label for="id_option_title">Option title</label>
                        <input type="text" name="option_title" id="id_option_title"><br />
                        <label for="id_is_correct">is_correct :</label><br />
                        <input type="radio" class="correct" name="is_correct_0" value="True">
                        <label for="html">True</label><br>
                        <input type="radio" class="wrong" name="is_correct_0" value="False">
                        <label for="css">False</label><br>
                </li>
                <li class="copy_node">
                        <label for="id_option_title">Option title</label>
                        <input type="text" name="option_title" id="id_option_title"><br />
                        <label for="id_is_correct">is_correct :</label><br />
                        <input type="radio" class="correct" name="is_correct_1" value="True">
                        <label for="html">True</label><br>
                        <input type="radio" class="wrong" name="is_correct_1" value="False">
                        <label for="css">False</label><br>
                </li>
                <li class="copy_node">
                        <label for="id_option_title">Option title</label>
                        <input type="text" name="option_title" id="id_option_title"><br />
                        <label for="id_is_correct">is_correct :</label><br />
                        <input type="radio" class="correct" name="is_correct_2" value="True">
                        <label for="html">True</label><br>
                        <input type="radio" class="wrong" name="is_correct_2" value="False">
                        <label for="css">False</label><br>
                </li>
                <li class="copy_node">
                        <label for="id_option_title">Option title</label>
                        <input type="text" name="option_title" id="id_option_title"><br />
                        <label for="id_is_correct">is_correct :</label><br />
                        <input type="radio" class="correct" name="is_correct_3" value="True">
                        <label for="html">True</label><br>
                        <input type="radio" class="wrong" name="is_correct_3" value="False">
                        <label for="css">False</label><br>
                </li>
               {# <button  id="id_button" type="button" onclick="getInputItem(this)" >+</button><br /><br /> #} 
            </ol>
            
            <button class='btn btn-info dash'  type="submit" value="submit">Submit</button>  <a class='btn btn-info dash' role='button' href="{% url 'quiz_app:teacher_dashboard' %}">Go Dashboard</a>
        </form>
    </div> 

    <!-- <script>
        let parent = document.querySelector("#options_group");
        let input_node = document.querySelector(".copy_node");
        let button = document.querySelector("#id_button");
        
        function getInputItem(e){

            if(e.previousSibling.tagName == 'LI') {
                // console.log('1' ,e.previousSibling)
                let i = parseInt(e.previousSibling.querySelector('.wrong').name.slice(-1));
                let input_node = e.previousSibling;
                var cln = input_node.cloneNode(true);
                // console.log('1',cln)
                let radio_button_wrong = cln.querySelector('.wrong');
                let radio_button_correct = cln.querySelector('.correct');
                radio_button_correct.name = `is_correct_${i+1}`;
                radio_button_wrong.name = `is_correct_${i+1}`;
            } else if (e.previousSibling.previousSibling.tagName == 'LI'){
                // console.log('2', e.previousSibling.previousSibling, typeof e.previousSibling.previousSibling)
                let i = parseInt(e.previousSibling.previousSibling.querySelector('.wrong').name.slice(-1));
                let input_node = e.previousSibling.previousSibling;
                var cln = input_node.cloneNode(true)
                // console.log('2',cln)
                let radio_button_wrong = cln.querySelector('.wrong');
                let radio_button_correct = cln.querySelector('.correct');
                radio_button_correct.name = `is_correct_${i+1}`;
                radio_button_wrong.name = `is_correct_${i+1}`;

            } 
            
            parent.insertBefore(cln, e);
        }

    </script> -->
    
</body>
</html>

quiz_app/templates/teacher/question_delete_view.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body class="bg-light">
    <div class="container">
        <div class="row">
          <div class="col-0 col-sm-2">
          
          </div>
          <div class="col-12 col-sm-8 bg-white shadow rounded-3 p-5 mt-5">
            
            <h3 class="">Examination Information</h3>
            <br />
            <br />
    <form method="POST" action="">
        {% csrf_token %}
        <h3>Are you sure you want to delete this Question?</h3>
         
        <input class="btn btn-danger" type="submit" value="Yes"/>

        <a class="btn btn-warning" href="{% url 'quiz_app:teacher_dashboard' %}">No </a>
        </form>
    </div>
 
    <div class="col-0 col-sm-2">
        
      </div>
    </div>
    </div>
</body>
</html>